name: React TS CI

on:
  push:

permissions:
  contents: write
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
        
      - name: Install dependencies
        run: npm install

      - name: Run coverage test
        run: npm run coverage
      
      - name: see scope
        run: ls
      
      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Tests
          path: coverage/*.xml
          reporter: java-junit
          fail-on-error: true

      - name: Upload coverage to GitHubPage
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: coverage/lcov-report # The folder the action should deploy.
          branch: coverage-deploy # The branch the action should deploy to.